micronaut:
    application:
        name: "blog-app"
    server:
        port: 8081
        cors:
            enabled: true
    router:
        static-resources:
            public:
                enabled: true
                mapping: "/**"
                paths: "classpath:public"


mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/blogs"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20